const http = require("http")
const server = http.createServer(function(req, res) {
    res.writeHead(200, { "Content-type": "text/html;charset=UTF8" })
    res.write("<ul>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("<li>hhhhhhhhh</li>")
    res.write("</ul>")
    res.end("成功！")
})
server.listen(8888)